### PR TITLE
Feature/super power

### PR DESCRIPTION
**Pull request by kostiakoval**
I think it would be cool to have a static typed struct that represent version. 
Use example

```
let v = Version("1.2.3")
let new = Version("1.2.4")
if new == v {
  // handle it
}
```

This is just a beginning ... 
We can add Comparable protocol to compare version 

```
let v = Version("1.0.1")
let newV = Version("1.2.1")
v > newV
v == newV
```

and more :)
What do you thing @zenangst ?

### CODE REVIEW

**Comment by zenangst** [comment]
I like this! :100:

**Comment by 3lvis** [comment]
Wonderful, wonderful ideas!

**Comment by 3lvis** [comment]
Specially the Comparable

**Comment by zenangst** [comment]
@kostiakoval ready to merge?

**Comment by kostiakoval** [comment]
@zenangst 
Nope. I need to update it to the latest our agreement #6 (Int, Int, Int, String)
Promise to fix it in evening!

**Comment by zenangst** [comment]
Don't forget the [WIP] title prefix for ongoing PR's :sunglasses:

**Comment by kostiakoval** [comment]
@zenangst Now it's done. Static versioning
Major, minor, patch, all Ints. Will add metadata in separate PR

**Comment by kostiakoval** [comment]
It's done

**Comment by kostiakoval** [comment]
See Next PR

**Pull request closed without merging**
